CREATE TABLE IF NOT EXISTS `biz_request_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `request_log_id` varchar(64) NOT NULL COMMENT '请求记录业务ID',
  `owner_user_id` bigint unsigned DEFAULT NULL COMMENT '归属用户ID',
  `owner_ref_id` varchar(64) NOT NULL DEFAULT '' COMMENT '归属业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务ID',
  `workflow_id` varchar(64) NOT NULL DEFAULT '' COMMENT '工作流ID',
  `request_type` varchar(64) NOT NULL DEFAULT '' COMMENT '请求类型',
  `stage` varchar(64) NOT NULL DEFAULT '' COMMENT '阶段',
  `operation` varchar(128) NOT NULL DEFAULT '' COMMENT '操作',
  `provider` varchar(64) NOT NULL DEFAULT '' COMMENT '模型厂商',
  `provider_model` varchar(128) NOT NULL DEFAULT '' COMMENT '厂商模型',
  `requested_model` varchar(128) NOT NULL DEFAULT '' COMMENT '请求模型',
  `resolved_model` varchar(128) NOT NULL DEFAULT '' COMMENT '实际模型',
  `endpoint_host` varchar(255) NOT NULL DEFAULT '' COMMENT '请求目标主机',
  `request_id` varchar(128) NOT NULL DEFAULT '' COMMENT '上游请求ID',
  `status` varchar(32) NOT NULL DEFAULT '' COMMENT '请求结果状态',
  `success` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否成功',
  `http_status` int NOT NULL DEFAULT '0' COMMENT 'HTTP状态码',
  `error_code` varchar(120) NOT NULL DEFAULT '' COMMENT '错误码',
  `error_message` text NOT NULL COMMENT '错误信息',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '请求开始时间',
  `finished_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '请求结束时间',
  `duration_ms` int unsigned NOT NULL DEFAULT '0' COMMENT '请求耗时毫秒',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_log_id` (`request_log_id`),
  KEY `idx_request_logs_owner_time` (`owner_user_id`, `started_at`),
  KEY `idx_request_logs_task_time` (`task_id`, `started_at`),
  KEY `idx_request_logs_workflow_time` (`workflow_id`, `started_at`),
  KEY `idx_request_logs_type_status_time` (`request_type`, `status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='请求记录日志表';
