CREATE TABLE IF NOT EXISTS `biz_tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_id` varchar(64) NOT NULL COMMENT '任务业务ID',
  `task_type` varchar(32) NOT NULL DEFAULT 'generation' COMMENT '任务类型',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '任务标题',
  `description` text COMMENT '任务描述',
  `aspect_ratio` varchar(16) NOT NULL DEFAULT '' COMMENT '画幅比例',
  `min_duration_seconds` int unsigned NOT NULL DEFAULT '0' COMMENT '最小时长秒',
  `max_duration_seconds` int unsigned NOT NULL DEFAULT '0' COMMENT '最大时长秒',
  `output_count` int unsigned NOT NULL DEFAULT '0' COMMENT '输出数量',
  `source_primary_asset_id` varchar(64) NOT NULL DEFAULT '' COMMENT '主来源素材ID',
  `source_file_name` varchar(255) NOT NULL DEFAULT '' COMMENT '来源文件名',
  `source_asset_ids_json` longtext COMMENT '来源素材ID列表',
  `source_file_names_json` longtext COMMENT '来源文件名列表',
  `request_payload_json` longtext COMMENT '请求快照',
  `context_json` longtext COMMENT '执行上下文',
  `intro_template` varchar(255) NOT NULL DEFAULT '' COMMENT '片头模板',
  `outro_template` varchar(255) NOT NULL DEFAULT '' COMMENT '片尾模板',
  `creative_prompt` text COMMENT '创意提示词',
  `task_seed` int DEFAULT NULL COMMENT '任务种子',
  `effect_rating` int DEFAULT NULL COMMENT '效果评分',
  `effect_rating_note` varchar(1000) NOT NULL DEFAULT '' COMMENT '效果评分备注',
  `rated_at` datetime DEFAULT NULL COMMENT '评分时间',
  `model_provider` varchar(64) NOT NULL DEFAULT '' COMMENT '模型提供方',
  `execution_mode` varchar(32) NOT NULL DEFAULT 'queue' COMMENT '执行模式',
  `editing_mode` varchar(32) NOT NULL DEFAULT '' COMMENT '编辑模式',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
  `progress` int unsigned NOT NULL DEFAULT '0' COMMENT '任务进度',
  `error_code` varchar(120) NOT NULL DEFAULT '' COMMENT '错误码',
  `error_message` text COMMENT '错误信息',
  `plan_json` longtext COMMENT '规划信息',
  `retry_count` int unsigned NOT NULL DEFAULT '0' COMMENT '重试次数',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_biz_tasks_status_create_time` (`status`, `create_time`),
  KEY `idx_biz_tasks_effect_rating` (`effect_rating`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务主表';

CREATE TABLE IF NOT EXISTS `biz_task_status_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_status_history_id` varchar(64) NOT NULL COMMENT '状态历史业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `previous_status` varchar(32) NOT NULL DEFAULT '' COMMENT '前一状态',
  `current_status` varchar(32) NOT NULL DEFAULT '' COMMENT '当前状态',
  `progress` int unsigned NOT NULL DEFAULT '0' COMMENT '状态进度',
  `stage` varchar(64) NOT NULL DEFAULT '' COMMENT '阶段名称',
  `event` varchar(128) NOT NULL DEFAULT '' COMMENT '事件名称',
  `message` text COMMENT '状态说明',
  `payload_json` longtext COMMENT '扩展载荷',
  `change_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '状态变更时间',
  `operator_type` varchar(32) NOT NULL DEFAULT '' COMMENT '操作方类型',
  `operator_id` varchar(64) NOT NULL DEFAULT '' COMMENT '操作方标识',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_status_history_id` (`task_status_history_id`),
  KEY `idx_task_status_history_task_time` (`task_id`, `change_time`),
  KEY `idx_task_status_history_current_status` (`current_status`, `change_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务状态变更历史表';

CREATE TABLE IF NOT EXISTS `biz_task_attempts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_attempt_id` varchar(64) NOT NULL COMMENT '任务尝试业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `attempt_no` int unsigned NOT NULL DEFAULT '1' COMMENT '尝试序号',
  `trigger_type` varchar(32) NOT NULL DEFAULT 'create' COMMENT '触发类型',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '尝试状态',
  `queue_name` varchar(128) NOT NULL DEFAULT '' COMMENT '队列名称',
  `worker_instance_id` varchar(64) NOT NULL DEFAULT '' COMMENT '执行 worker 实例ID',
  `queue_entered_at` datetime DEFAULT NULL COMMENT '进入队列时间',
  `queue_left_at` datetime DEFAULT NULL COMMENT '离开队列时间',
  `claimed_at` datetime DEFAULT NULL COMMENT '被 worker claim 时间',
  `started_at` datetime DEFAULT NULL COMMENT '开始执行时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `resume_from_stage` varchar(64) NOT NULL DEFAULT '' COMMENT '恢复起始阶段',
  `resume_from_clip_index` int NOT NULL DEFAULT '0' COMMENT '恢复起始镜头',
  `failure_code` varchar(120) NOT NULL DEFAULT '' COMMENT '失败码',
  `failure_message` text NOT NULL COMMENT '失败信息',
  `payload_json` json NOT NULL COMMENT '尝试快照',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_attempt_id` (`task_attempt_id`),
  UNIQUE KEY `uk_task_attempts_task_no` (`task_id`, `attempt_no`),
  KEY `idx_task_attempts_status_queue_entered_at` (`status`, `queue_entered_at`),
  KEY `idx_task_attempts_worker_status` (`worker_instance_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务执行尝试表';

CREATE TABLE IF NOT EXISTS `biz_task_stage_runs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_stage_run_id` varchar(64) NOT NULL COMMENT '阶段运行业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `attempt_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务尝试ID',
  `stage_name` varchar(64) NOT NULL DEFAULT '' COMMENT '阶段名称',
  `stage_seq` int unsigned NOT NULL DEFAULT '1' COMMENT '阶段序号',
  `clip_index` int NOT NULL DEFAULT '0' COMMENT '镜头序号',
  `status` varchar(32) NOT NULL DEFAULT 'RUNNING' COMMENT '阶段状态',
  `worker_instance_id` varchar(64) NOT NULL DEFAULT '' COMMENT '执行 worker 实例ID',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `duration_ms` int unsigned NOT NULL DEFAULT '0' COMMENT '阶段耗时毫秒',
  `input_summary_json` json NOT NULL COMMENT '输入摘要',
  `output_summary_json` json NOT NULL COMMENT '输出摘要',
  `error_code` varchar(120) NOT NULL DEFAULT '' COMMENT '错误码',
  `error_message` text NOT NULL COMMENT '错误信息',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_stage_run_id` (`task_stage_run_id`),
  KEY `idx_task_stage_runs_attempt_stage` (`attempt_id`, `stage_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务阶段执行表';

CREATE TABLE IF NOT EXISTS `biz_task_queue_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_queue_event_id` varchar(64) NOT NULL COMMENT '队列事件业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `attempt_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务尝试ID',
  `queue_name` varchar(128) NOT NULL DEFAULT '' COMMENT '队列名称',
  `event_type` varchar(32) NOT NULL DEFAULT '' COMMENT '队列事件类型',
  `worker_instance_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'worker 实例ID',
  `queue_position_hint` int NOT NULL DEFAULT '0' COMMENT '队列位置提示',
  `payload_json` json NOT NULL COMMENT '扩展载荷',
  `event_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事件时间',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_queue_event_id` (`task_queue_event_id`),
  KEY `idx_task_queue_events_task_time` (`task_id`, `event_time`),
  KEY `idx_task_queue_events_attempt_time` (`attempt_id`, `event_time`),
  KEY `idx_task_queue_events_worker_time` (`worker_instance_id`, `event_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务队列事件表（入队/claim/重入队/完成等）';

CREATE TABLE IF NOT EXISTS `biz_worker_instances` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `worker_instance_id` varchar(64) NOT NULL COMMENT 'worker 实例业务ID',
  `worker_type` varchar(32) NOT NULL DEFAULT 'standalone_worker' COMMENT 'worker 类型',
  `queue_name` varchar(128) NOT NULL DEFAULT '' COMMENT '队列名称',
  `host_name` varchar(128) NOT NULL DEFAULT '' COMMENT '主机名',
  `process_id` int NOT NULL DEFAULT '0' COMMENT '进程ID',
  `status` varchar(32) NOT NULL DEFAULT 'RUNNING' COMMENT '实例状态',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '启动时间',
  `last_heartbeat_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后心跳时间',
  `stopped_at` datetime DEFAULT NULL COMMENT '停止时间',
  `metadata_json` json NOT NULL COMMENT '扩展元数据',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_worker_instance_id` (`worker_instance_id`),
  KEY `idx_worker_instances_status_heartbeat` (`status`, `last_heartbeat_at`),
  KEY `idx_worker_instances_type_started` (`worker_type`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Worker 实例表（进程存活、心跳、类型）';

CREATE TABLE IF NOT EXISTS `biz_task_model_calls` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_model_call_id` varchar(64) NOT NULL COMMENT '模型调用业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `call_kind` varchar(32) NOT NULL DEFAULT '' COMMENT '调用类型',
  `stage` varchar(64) NOT NULL DEFAULT '' COMMENT '调用阶段',
  `operation` varchar(64) NOT NULL DEFAULT '' COMMENT '操作名',
  `provider` varchar(64) NOT NULL DEFAULT '' COMMENT '模型提供方',
  `provider_model` varchar(128) NOT NULL DEFAULT '' COMMENT '提供方模型名',
  `requested_model` varchar(128) NOT NULL DEFAULT '' COMMENT '请求模型名',
  `resolved_model` varchar(128) NOT NULL DEFAULT '' COMMENT '最终模型名',
  `model_name` varchar(128) NOT NULL DEFAULT '' COMMENT '模型名',
  `model_alias` varchar(128) NOT NULL DEFAULT '' COMMENT '模型别名',
  `endpoint_host` varchar(255) NOT NULL DEFAULT '' COMMENT '请求目标主机',
  `request_id` varchar(128) NOT NULL DEFAULT '' COMMENT '上游请求ID',
  `request_payload_json` json NOT NULL COMMENT '请求参数',
  `response_payload_json` json NOT NULL COMMENT '响应参数',
  `http_status` int NOT NULL DEFAULT '0' COMMENT 'HTTP状态码',
  `response_status_code` int NOT NULL DEFAULT '0' COMMENT 'HTTP状态码兼容字段',
  `success` tinyint(1) NOT NULL DEFAULT '0' COMMENT '调用是否成功',
  `error_code` varchar(120) NOT NULL DEFAULT '' COMMENT '错误码',
  `error_message` text NOT NULL COMMENT '错误信息',
  `latency_ms` int unsigned NOT NULL DEFAULT '0' COMMENT '时延毫秒',
  `duration_ms` int unsigned NOT NULL DEFAULT '0' COMMENT '耗时毫秒',
  `input_tokens` int unsigned NOT NULL DEFAULT '0' COMMENT '输入 token',
  `output_tokens` int unsigned NOT NULL DEFAULT '0' COMMENT '输出 token',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '调用开始时间',
  `finished_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '调用结束时间',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_model_call_id` (`task_model_call_id`),
  KEY `idx_task_model_calls_task_id_start_time` (`task_id`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务模型调用记录表';

CREATE TABLE IF NOT EXISTS `biz_task_results` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_result_id` varchar(64) NOT NULL COMMENT '任务结果业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `result_type` varchar(32) NOT NULL DEFAULT 'video' COMMENT '结果类型',
  `clip_index` int unsigned NOT NULL DEFAULT '0' COMMENT '结果序号',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '结果标题',
  `reason` text NOT NULL COMMENT '结果说明',
  `source_model_call_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源模型调用ID',
  `material_asset_id` varchar(64) NOT NULL DEFAULT '' COMMENT '结果素材ID',
  `start_seconds` double NOT NULL DEFAULT '0' COMMENT '起始秒',
  `end_seconds` double NOT NULL DEFAULT '0' COMMENT '结束秒',
  `duration_seconds` double NOT NULL DEFAULT '0' COMMENT '时长秒',
  `preview_path` text NOT NULL COMMENT '预览路径',
  `download_path` text NOT NULL COMMENT '下载路径',
  `width` int unsigned NOT NULL DEFAULT '0' COMMENT '宽度',
  `height` int unsigned NOT NULL DEFAULT '0' COMMENT '高度',
  `mime_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'MIME 类型',
  `size_bytes` bigint unsigned NOT NULL DEFAULT '0' COMMENT '文件大小',
  `remote_url` text NOT NULL COMMENT '远端结果地址',
  `extra_json` json NOT NULL COMMENT '扩展字段',
  `produced_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结果产出时间',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_result_id` (`task_result_id`),
  UNIQUE KEY `uk_task_results_task_clip` (`task_id`, `clip_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务结果表';

CREATE TABLE IF NOT EXISTS `biz_system_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `system_log_id` varchar(64) NOT NULL COMMENT '日志业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '关联任务ID',
  `trace_id` varchar(128) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
  `module` varchar(64) NOT NULL DEFAULT '' COMMENT '模块名',
  `stage` varchar(64) NOT NULL DEFAULT '' COMMENT '阶段',
  `event` varchar(128) NOT NULL DEFAULT '' COMMENT '事件',
  `level` varchar(16) NOT NULL DEFAULT 'INFO' COMMENT '日志级别',
  `message` text NOT NULL COMMENT '日志消息',
  `payload_json` json NOT NULL COMMENT '日志扩展参数',
  `source` varchar(64) NOT NULL DEFAULT 'backend' COMMENT '日志来源',
  `service_name` varchar(64) NOT NULL DEFAULT 'pipeline' COMMENT '服务名称',
  `host_name` varchar(128) NOT NULL DEFAULT '' COMMENT '主机名',
  `logged_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日志时间',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_log_id` (`system_log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统日志表';

CREATE TABLE IF NOT EXISTS `biz_material_assets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `material_asset_id` varchar(64) NOT NULL COMMENT '素材业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '关联任务ID',
  `source_task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源任务ID',
  `source_material_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源素材ID',
  `asset_role` varchar(32) NOT NULL DEFAULT 'source' COMMENT '素材角色',
  `media_type` varchar(32) NOT NULL DEFAULT 'video' COMMENT '媒体类型',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '素材标题',
  `origin_provider` varchar(64) NOT NULL DEFAULT '' COMMENT '来源提供方',
  `origin_model` varchar(128) NOT NULL DEFAULT '' COMMENT '来源模型',
  `remote_task_id` varchar(128) NOT NULL DEFAULT '' COMMENT '第三方任务ID',
  `remote_asset_id` varchar(128) NOT NULL DEFAULT '' COMMENT '第三方素材ID',
  `original_file_name` varchar(512) NOT NULL DEFAULT '' COMMENT '原始文件名',
  `stored_file_name` varchar(512) NOT NULL DEFAULT '' COMMENT '存储文件名',
  `file_ext` varchar(32) NOT NULL DEFAULT '' COMMENT '文件后缀',
  `storage_provider` varchar(32) NOT NULL DEFAULT 'local' COMMENT '存储提供方',
  `mime_type` varchar(255) NOT NULL DEFAULT '' COMMENT 'MIME 类型',
  `size_bytes` bigint unsigned NOT NULL DEFAULT '0' COMMENT '文件大小',
  `sha256` varchar(128) NOT NULL DEFAULT '' COMMENT '文件哈希',
  `duration_seconds` double NOT NULL DEFAULT '0' COMMENT '时长秒',
  `width` int unsigned NOT NULL DEFAULT '0' COMMENT '宽度',
  `height` int unsigned NOT NULL DEFAULT '0' COMMENT '高度',
  `has_audio` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否有音轨',
  `local_storage_path` text NOT NULL COMMENT '本地相对路径',
  `local_file_path` text NOT NULL COMMENT '本地绝对路径',
  `public_url` text NOT NULL COMMENT '对外访问 URL',
  `third_party_url` text NOT NULL COMMENT '第三方 URL',
  `remote_url` text NOT NULL COMMENT '远端 URL',
  `metadata_json` json NOT NULL COMMENT '素材扩展元数据',
  `captured_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '采集时间',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_material_asset_id` (`material_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='素材表';

CREATE TABLE IF NOT EXISTS `sys_user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `username` varchar(64) NOT NULL COMMENT '登录用户名',
  `display_name` varchar(128) NOT NULL DEFAULT '' COMMENT '显示名称',
  `password_hash` varchar(255) NOT NULL COMMENT '密码哈希',
  `role` varchar(16) NOT NULL DEFAULT 'USER' COMMENT '角色',
  `status` varchar(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
  `last_login_at` datetime DEFAULT NULL COMMENT '最近登录时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_username` (`username`),
  KEY `idx_sys_user_role_status` (`role`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS `sys_invite_code` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `code` varchar(64) NOT NULL COMMENT '邀请码',
  `role` varchar(16) NOT NULL DEFAULT 'USER' COMMENT '邀请码角色',
  `status` varchar(16) NOT NULL DEFAULT 'UNUSED' COMMENT '邀请码状态',
  `expires_at` datetime DEFAULT NULL COMMENT '过期时间',
  `created_by` bigint unsigned DEFAULT NULL COMMENT '创建人ID',
  `used_by` bigint unsigned DEFAULT NULL COMMENT '使用人ID',
  `used_at` datetime DEFAULT NULL COMMENT '使用时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_invite_code_code` (`code`),
  KEY `idx_sys_invite_code_status_expires` (`status`, `expires_at`),
  KEY `idx_sys_invite_code_created_by` (`created_by`),
  KEY `idx_sys_invite_code_used_by` (`used_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统邀请码表';
