-- Task-centric 6-table MySQL schema.
-- Business time semantics: UTC+8 (Asia/Shanghai).

CREATE TABLE IF NOT EXISTS `biz_tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_id` varchar(64) NOT NULL COMMENT '任务业务ID',
  `task_type` varchar(32) NOT NULL DEFAULT 'generation' COMMENT '任务类型',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '任务标题',
  `description` text NOT NULL COMMENT '任务描述',
  `platform` varchar(64) NOT NULL DEFAULT '' COMMENT '投放平台',
  `aspect_ratio` varchar(16) NOT NULL DEFAULT '' COMMENT '画幅比例',
  `min_duration_seconds` int unsigned NOT NULL DEFAULT '0' COMMENT '最小时长(秒)',
  `max_duration_seconds` int unsigned NOT NULL DEFAULT '0' COMMENT '最大时长(秒)',
  `output_count` int unsigned NOT NULL DEFAULT '1' COMMENT '输出数量',
  `source_primary_asset_id` varchar(64) NOT NULL DEFAULT '' COMMENT '主源素材ID',
  `source_file_name` varchar(512) NOT NULL DEFAULT '' COMMENT '主源素材文件名',
  `source_asset_ids_json` json NOT NULL COMMENT '源素材ID列表',
  `source_file_names_json` json NOT NULL COMMENT '源素材文件名列表',
  `request_payload_json` json NOT NULL COMMENT '任务请求快照',
  `context_json` json NOT NULL COMMENT '任务上下文',
  `intro_template` varchar(64) NOT NULL DEFAULT 'none' COMMENT '片头模板',
  `outro_template` varchar(64) NOT NULL DEFAULT 'none' COMMENT '片尾模板',
  `creative_prompt` text NOT NULL COMMENT '创意提示词',
  `model_provider` varchar(64) NOT NULL DEFAULT '' COMMENT '模型提供方',
  `execution_mode` varchar(32) NOT NULL DEFAULT '' COMMENT '执行模式',
  `editing_mode` varchar(32) NOT NULL DEFAULT 'drama' COMMENT '编辑模式',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
  `progress` int unsigned NOT NULL DEFAULT '0' COMMENT '任务进度',
  `error_code` varchar(120) NOT NULL DEFAULT '' COMMENT '错误码',
  `error_message` text NOT NULL COMMENT '错误信息',
  `plan_json` text NOT NULL COMMENT '规划结果JSON',
  `retry_count` int unsigned NOT NULL DEFAULT '0' COMMENT '重试次数',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间（UTC+8语义）',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间（UTC+8语义）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_tasks_status_create_time` (`status`,`create_time`),
  KEY `idx_tasks_platform_create_time` (`platform`,`create_time`),
  KEY `idx_tasks_source_primary_asset_id` (`source_primary_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务主表（业务时间语义：UTC+8）';


CREATE TABLE IF NOT EXISTS `biz_task_status_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_status_history_id` varchar(64) NOT NULL COMMENT '状态记录业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `previous_status` varchar(32) NOT NULL DEFAULT '' COMMENT '变更前状态',
  `current_status` varchar(32) NOT NULL DEFAULT '' COMMENT '变更后状态',
  `progress` int unsigned NOT NULL DEFAULT '0' COMMENT '状态变更时进度',
  `stage` varchar(64) NOT NULL DEFAULT '' COMMENT '处理阶段',
  `event` varchar(128) NOT NULL DEFAULT '' COMMENT '事件名称',
  `message` text NOT NULL COMMENT '事件消息',
  `payload_json` json NOT NULL COMMENT '扩展载荷',
  `change_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '状态变更时间（UTC+8语义）',
  `operator_type` varchar(32) NOT NULL DEFAULT 'system' COMMENT '操作者类型',
  `operator_id` varchar(64) NOT NULL DEFAULT '' COMMENT '操作者标识',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_status_history_id` (`task_status_history_id`),
  KEY `idx_task_status_history_task_id_change_time` (`task_id`,`change_time`),
  KEY `idx_task_status_history_current_status` (`current_status`,`change_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务状态变更记录表（业务时间语义：UTC+8）';


CREATE TABLE IF NOT EXISTS `biz_task_model_calls` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_model_call_id` varchar(64) NOT NULL COMMENT '模型调用业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `call_kind` varchar(32) NOT NULL DEFAULT '' COMMENT '调用类型',
  `stage` varchar(64) NOT NULL DEFAULT '' COMMENT '调用阶段',
  `operation` varchar(64) NOT NULL DEFAULT '' COMMENT '操作名',
  `provider` varchar(64) NOT NULL DEFAULT '' COMMENT '模型提供方',
  `provider_model` varchar(128) NOT NULL DEFAULT '' COMMENT '提供方模型名',
  `requested_model` varchar(128) NOT NULL DEFAULT '' COMMENT '请求模型名',
  `resolved_model` varchar(128) NOT NULL DEFAULT '' COMMENT '最终模型名',
  `model_name` varchar(128) NOT NULL DEFAULT '' COMMENT '模型名（兼容字段）',
  `model_alias` varchar(128) NOT NULL DEFAULT '' COMMENT '模型别名（兼容字段）',
  `endpoint_host` varchar(255) NOT NULL DEFAULT '' COMMENT '请求目标主机',
  `request_id` varchar(128) NOT NULL DEFAULT '' COMMENT '上游请求ID',
  `request_payload_json` json NOT NULL COMMENT '请求参数',
  `response_payload_json` json NOT NULL COMMENT '响应参数',
  `http_status` int NOT NULL DEFAULT '0' COMMENT 'HTTP状态码',
  `response_status_code` int NOT NULL DEFAULT '0' COMMENT 'HTTP状态码（兼容字段）',
  `success` tinyint(1) NOT NULL DEFAULT '0' COMMENT '调用是否成功',
  `error_code` varchar(120) NOT NULL DEFAULT '' COMMENT '错误码',
  `error_message` text NOT NULL COMMENT '错误信息',
  `latency_ms` int unsigned NOT NULL DEFAULT '0' COMMENT '时延毫秒',
  `duration_ms` int unsigned NOT NULL DEFAULT '0' COMMENT '调用耗时ms（兼容字段）',
  `input_tokens` int unsigned NOT NULL DEFAULT '0' COMMENT '输入token',
  `output_tokens` int unsigned NOT NULL DEFAULT '0' COMMENT '输出token',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '调用开始时间（UTC+8语义）',
  `finished_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '调用结束时间（UTC+8语义）',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_model_call_id` (`task_model_call_id`),
  KEY `idx_task_model_calls_task_id_start_time` (`task_id`,`started_at`),
  KEY `idx_task_model_calls_provider_model` (`provider`,`model_name`),
  KEY `idx_task_model_calls_success_start_time` (`success`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务模型调用记录表（请求/响应全链路，业务时间语义：UTC+8）';


CREATE TABLE IF NOT EXISTS `biz_task_results` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_result_id` varchar(64) NOT NULL COMMENT '任务结果业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '任务业务ID',
  `result_type` varchar(32) NOT NULL DEFAULT 'video' COMMENT '结果类型',
  `clip_index` int unsigned NOT NULL DEFAULT '0' COMMENT '结果序号',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '结果标题',
  `reason` text NOT NULL COMMENT '结果说明',
  `source_model_call_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源模型调用ID',
  `material_asset_id` varchar(64) NOT NULL DEFAULT '' COMMENT '结果素材ID',
  `start_seconds` double NOT NULL DEFAULT '0' COMMENT '起始秒',
  `end_seconds` double NOT NULL DEFAULT '0' COMMENT '结束秒',
  `duration_seconds` double NOT NULL DEFAULT '0' COMMENT '时长秒',
  `preview_path` text NOT NULL COMMENT '预览路径',
  `download_path` text NOT NULL COMMENT '下载路径',
  `width` int unsigned NOT NULL DEFAULT '0' COMMENT '宽度',
  `height` int unsigned NOT NULL DEFAULT '0' COMMENT '高度',
  `mime_type` varchar(128) NOT NULL DEFAULT '' COMMENT 'MIME类型',
  `size_bytes` bigint unsigned NOT NULL DEFAULT '0' COMMENT '文件大小字节',
  `remote_url` text NOT NULL COMMENT '第三方结果地址',
  `extra_json` json NOT NULL COMMENT '扩展字段',
  `produced_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结果产出时间（UTC+8语义）',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_result_id` (`task_result_id`),
  UNIQUE KEY `uk_task_results_task_clip` (`task_id`,`clip_index`),
  KEY `idx_task_results_task_id_clip_index` (`task_id`,`clip_index`),
  KEY `idx_task_results_material_asset_id` (`material_asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务结果表（视频/图片/文本等输出记录）';


CREATE TABLE IF NOT EXISTS `biz_system_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `system_log_id` varchar(64) NOT NULL COMMENT '日志业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '关联任务ID',
  `trace_id` varchar(128) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
  `module` varchar(64) NOT NULL DEFAULT '' COMMENT '模块名',
  `stage` varchar(64) NOT NULL DEFAULT '' COMMENT '阶段',
  `event` varchar(128) NOT NULL DEFAULT '' COMMENT '事件',
  `level` varchar(16) NOT NULL DEFAULT 'INFO' COMMENT '日志级别',
  `message` text NOT NULL COMMENT '日志消息',
  `payload_json` json NOT NULL COMMENT '日志扩展参数',
  `source` varchar(64) NOT NULL DEFAULT 'backend' COMMENT '日志来源',
  `service_name` varchar(64) NOT NULL DEFAULT 'pipeline' COMMENT '服务名称',
  `host_name` varchar(128) NOT NULL DEFAULT '' COMMENT '主机名',
  `logged_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日志时间（UTC+8语义）',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_log_id` (`system_log_id`),
  KEY `idx_system_logs_task_id_logged_at` (`task_id`,`logged_at`),
  KEY `idx_system_logs_level_logged_at` (`level`,`logged_at`),
  KEY `idx_system_logs_module_stage` (`module`,`stage`,`logged_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统日志表（全项目日志统一沉淀，业务时间语义：UTC+8）';


CREATE TABLE IF NOT EXISTS `biz_material_assets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `material_asset_id` varchar(64) NOT NULL COMMENT '素材业务ID',
  `task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '关联任务ID',
  `source_task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源任务ID',
  `source_material_id` varchar(64) NOT NULL DEFAULT '' COMMENT '来源素材ID（兼容字段）',
  `asset_role` varchar(32) NOT NULL DEFAULT 'source' COMMENT '素材角色',
  `media_type` varchar(32) NOT NULL DEFAULT 'video' COMMENT '媒体类型',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT '素材标题',
  `origin_provider` varchar(64) NOT NULL DEFAULT '' COMMENT '来源提供方',
  `origin_model` varchar(128) NOT NULL DEFAULT '' COMMENT '来源模型',
  `remote_task_id` varchar(128) NOT NULL DEFAULT '' COMMENT '第三方任务ID',
  `remote_asset_id` varchar(128) NOT NULL DEFAULT '' COMMENT '第三方素材ID',
  `original_file_name` varchar(512) NOT NULL DEFAULT '' COMMENT '原始文件名',
  `stored_file_name` varchar(512) NOT NULL DEFAULT '' COMMENT '存储文件名',
  `file_ext` varchar(32) NOT NULL DEFAULT '' COMMENT '文件后缀',
  `storage_provider` varchar(32) NOT NULL DEFAULT 'local' COMMENT '存储提供方',
  `mime_type` varchar(255) NOT NULL DEFAULT '' COMMENT 'MIME类型',
  `size_bytes` bigint unsigned NOT NULL DEFAULT '0' COMMENT '文件大小字节',
  `sha256` varchar(128) NOT NULL DEFAULT '' COMMENT '内容哈希',
  `duration_seconds` double NOT NULL DEFAULT '0' COMMENT '时长秒',
  `width` int unsigned NOT NULL DEFAULT '0' COMMENT '宽度',
  `height` int unsigned NOT NULL DEFAULT '0' COMMENT '高度',
  `has_audio` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否有音轨',
  `local_storage_path` text NOT NULL COMMENT '本地相对存储路径',
  `local_file_path` text NOT NULL COMMENT '本地绝对路径',
  `public_url` text NOT NULL COMMENT '对外访问URL',
  `third_party_url` text NOT NULL COMMENT '第三方URL（兼容字段）',
  `remote_url` text NOT NULL COMMENT '第三方URL',
  `metadata_json` json NOT NULL COMMENT '素材扩展元数据',
  `captured_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '素材采集时间（UTC+8语义）',
  `timezone_offset_minutes` int NOT NULL DEFAULT '480' COMMENT '业务时区偏移分钟（东八区=480）',
  `is_deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-未删, 1-已删',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间（业务时区：UTC+8）',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间（业务时区：UTC+8）',
  `remark` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_material_asset_id` (`material_asset_id`),
  KEY `idx_material_assets_task_id_role_create_time` (`task_id`,`asset_role`,`create_time`),
  KEY `idx_material_assets_sha256` (`sha256`),
  KEY `idx_material_assets_remote_task_id` (`remote_task_id`),
  KEY `idx_material_assets_media_type_create_time` (`media_type`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='素材表（源素材/中间素材/结果素材统一管理，业务时间语义：UTC+8）';
